- podpac/core/algorithm/algorithm.py
@mpu-creare I added a check and exception for empty equations instead of relying on a default. The default surprised me during testing.
> Removes default eqn in the Arithmetic node

- podpac/core/pipeline/output.py
The try-except that hid the actual error is also removed. I think that user code that needs to catch that exception should have it's own try-except. Is that okay?
> HOTFIX: The ImageOutput image trait type is reverted to Bytes.

- podpac/core/coordinates/cfunctions.py
> Adds name argument to crange and clinspace.

- doc/source/developer/contributing.md
- podpac/core/data/datasource.py
- podpac/core/test/test_utils.py
- podpac/core/utils.py
This includes one util method for creating podpac only log handler - i'm open to removing this, but this seems like a good middle road.
BasicConfig will work for most people, but unfortuantely there is no way to configure this to be a podpac only logger (i.e. you get all other module logging as well). This util method will create a log file with a specific format that has podpac ONLY logs.
> FEATURE: second attempt at the log - see contributing.md "## Logging"

- doc/source/developer/contributing.md
- podpac/core/coordinates/array_coordinates1d.py
- podpac/core/coordinates/coordinates1d.py
- podpac/core/coordinates/uniform_coordinates1d.py
A wrote a class decorator to set the `__doc__` strings for `class_traits`, but that didn't work for a few reasons. What do you think of this? It is the basically the same as writing  `#:` or `""" """` docstrings that Sphinx picks up (and Sphinx displays them exactly the same), but they are inherited properly.
> Sets attribute __doc__ strings directly so that they will be inherited

- podpac/core/data/datasource.py
- podpac/core/data/test/test_datasource.py
I think this is a pretty simple/solid PR, but I just wanted to run it by you. I thought I would need to transpose the coordinates *earlier* so that `self._requested_source_coordinates` would also be transposed, but tests seem to be working so maybe this is just fine.
> Fix datasource eval when output is provided

- podpac/core/data/types.py
NumpyArray was marked for deprecation in 0.2.0 and I guess we missed that. I think we should remove it for 1.0.0.
The `Node.style` attribute is also marked for deprecation also, but I didn't remove it. Should we (can we) remove it?
I didn't find anything else.
> Removes deprecated NumpyArray, etc

- podpac/core/coordinates/coordinates.py
- podpac/core/coordinates/stacked_coordinates.py
- podpac/core/coordinates/test/test_coordinates.py
- podpac/core/coordinates/test/test_stacked_coordinates.py
This would be helpful to me since I would not have to figure out how dimensions are stacked in order to set them. It seems like there was a good reason to keep the StackedCoordinates components read only - feel free to reject this PR if this goes against a design consideration
Example:
stack_coords = Coordinates([(np.linspace(-10, 10, 21), np.linspace(-30, -10, 21))], dims=['lat_lon'])
stack_coords['lat'] = np.linspace(-50, -10, 21)
stack_coords['lat_lon']['lat'] = np.linspace(-50, -10, 21)  # also works
> ENH: allow stacked dimensions to be set from Coordinates or StackedCoordinates

- podpac/core/pipeline/pipeline.py
- podpac/core/pipeline/test/test.json
- podpac/core/pipeline/test/test_pipeline.py
The change here is very small, and may be sufficient to close #110. See `test_debuggable` in the pipeline tests and the change in `_get_subattr`. I am only copying nodes if debugging is on, but we could also just always deepcopy if you want.
This PR also includes also bugfixes so that pipelines load json definition as OrderedDict.
> In pipelines, nodes are copied when debugging is on, to help when debugging.

- podpac/core/algorithm/algorithm.py
- podpac/core/algorithm/coord_select.py
- podpac/core/algorithm/signal.py
- podpac/core/algorithm/stats.py
- podpac/core/algorithm/test/test_signal.py
- podpac/core/data/types.py
- podpac/core/utils.py
This is a proposed additional fix for #110.
Instead of only copying nodes in pipelines, this copies nodes in all cases when debugging is on.
This example is from `test_debuggable_source` in the `test_signal.py`:
Normal usage:
```
a = Arange()
node = Convolution(source=a, kernel=[[1, 2, 1]], kernel_ndim=2)
node.eval(coords)
assert node.source is a
```
Debugging:
```
settings['DEBUG'] = True
a = Arange()
node = Convolution(source=a, kernel=[[1, 2, 1]], kernel_ndim=2)
node.eval(coords)
assert node.source is not a
assert node._requested_coordinates is not None
assert node.source._requested_coordinates is not None
assert a._requested_coordinates is None
```
> Automatically copies node traits when debug is on.

- podpac/core/cache/cache.py
Uses `# pragma: no cover` to exclude some S3 code from the coverage report:
* `S3CacheStore`
> S3 test coverage

- podpac/core/data/datasource.py
- podpac/core/data/test/test_interpolate.py
- podpac/core/data/test/test_types.py
- podpac/core/data/types.py
- podpac/core/node.py
- podpac/core/test/test_node.py
- podpac/datalib/gfs.py
- podpac/datalib/intake.py
- podpac/datalib/smap.py
- podpac/datalib/terraintiles.py
Node traits tagged as 'readonly' or as 'attr' can be specified using keyword arguments during Node instatiation, but cannot be later modified. It uses the `read_only` flag under the hood but is a slightly more flexible.
```
class MyDataSource(DataSource)
source = tl.Unicode().tag(readonly=True)
my_attr = tl.Int().tag(attr=True)
```
```
>>> node = MyDataSource(source='mysource', my_attr=8)
>>> node.source = 'other'
...
traitlets.traitlets.TraitError: The "source" trait is read-only.
>>> node.my_attr = 6
traitlets.traitlets.TraitError: The "my_attr" trait is read-only.
```
> general readonly tag

- podpac/core/data/datasource.py
- podpac/core/data/test/test_types.py
- podpac/core/data/types.py
- podpac/datalib/intake.py
- podpac/datalib/smap.py
- podpac/datalib/terraintiles.py
* I set `source`, `native_coordinates` and `dataset` traits as read_only.
* Traitlets does not allow read_only traits to be set at initialization, so I added a simple workaround in the DataSource `_first_init`.
* I removed code handling source changes.
* Note: `set_trait` still works for read_only traits in a pinch.
* A general solution to making tagged node attrs read-only coming soon.
This is an issue we've been punting on for a while. I am unifying some of the "dataset" based datasources for the multiple outputs feature, and it is a good time to do this.
> Readonly source, native_coordinates (and dataset) traits

- podpac/core/algorithm/stats.py
- podpac/core/cache/test/test_cache_stores.py
- podpac/core/coordinates/test/test_coordinates.py
- podpac/core/coordinates/test/test_uniform_coordinates1d.py
- podpac/core/coordinates/uniform_coordinates1d.py
- podpac/core/data/interpolation.py
- podpac/core/data/interpolator.py
- podpac/core/data/interpolators.py
- podpac/core/data/test/test_datasource.py
- podpac/core/data/test/test_interpolate.py
- podpac/core/data/test/test_types.py
- setup.cfg
On my machine, our tests pass with 700+ warnings.
In this PR, warnings are treated as errors by pytest. All warnings are fixed by globally filtering certain warnings, catching expected warnings, or fixing bugs in podpac.
Bugfixes:
- (core/algorithm/stats.py) multi-indexes should be tuples, not lists
- (core/coordinates/uniform_coordinates1d.py) `np.timedelta64` cannot be compared directly with 0
- (core/coordinates/uniform_coordinates1d.py) uniform coordinates *do* need to check `start`, `stop`, and `step`
- (core/data/interpolation.py) numpy arrays cannot be compared with `==`
- (core/data/interpolator.py) `spatial_tolerance` should be defined as a trait for the base interpolator
> Tests should run without warnings.

- podpac/core/node.py
- podpac/core/pipeline/pipeline.py
- podpac/core/style.py
- podpac/core/test/test_node.py
- podpac/core/test/test_style.py
- podpac/datalib/drought_monitor.py
The Style serialization itself is updated so that the definition will be empty for the default style, which allows the node definition to omit the style when it is not necessary.
```python
>>> style = Style()
>>> style.definition
OrderedDict()
>>> style=Style(name="test")
>>> style.definition
OrderedDict([('name', 'test')])
>>> node = Node()
>>> node.definition
OrderedDict([('Node', OrderedDict([('node', 'core.node.Node')]))])
>>> node = Node(style=Style(name="test"))
OrderedDict([('Node', OrderedDict([('node', 'core.node.Node'), ('style', OrderedDict([('name', 'test')]))]))])
```
In order to do that, I modified the Style cmap handling, so that `colormap` is string trait (that can be None) and `cmap` is a property that either uses `colormap`, `enumeration_colors`, or a default:
```python …
```
> Adds style to node serialization. 

- podpac/core/data/datasource.py
- podpac/core/data/interpolation.py
- podpac/core/data/test/test_interpolate.py
- podpac/core/utils.py
Fixes #320 with new specification for interpolation definitions:
```
interp = {
'method': 'nearest',
'interpolators': [podpac.interpolators.ScipyGrid, NearestNeighbor, ...],
'dims': ['lat', 'lon'], 
}            
interpolation = [
interp, 
{'method': 'bilinear', 
'dims': ['time']}
]
```
> FIX #320: update interpolation definition

- podpac/core/algorithm/generic.py
- podpac/core/algorithm/test/test_algorithm.py
- podpac/core/algorithm/test/test_generic.py
- podpac/core/algorithm/test/test_signal.py
- podpac/core/algorithm/test/test_stats.py
- podpac/core/cache/test/test_cache_ctrl.py
- podpac/core/coordinates/test/test_array_coordinates1d.py
- podpac/core/coordinates/test/test_coordinates.py
- podpac/core/data/test/test_types.py
- podpac/core/node.py
- podpac/core/pipeline/test/test_parse_pipeline_definition.py
- podpac/core/pipeline/test/test_pipeline.py
- podpac/core/settings.py
- podpac/core/test/test_compositor.py
- podpac/core/test/test_node.py
- podpac/datalib/drought_monitor.py
Pretty simple, the settings can be used in a context manager to restore original settings after exiting a block.
```
with podpac.settings:
podpac.settings["CACHE_OUTPUT_DEFAUL"] = False
...
assert podpac.settings["CACHE_OUTPUT_DEFAULT"] == True
```
This can replace setup_method and teardown_method in tests, which is what I used it for here, but it seems useful in general. If you like it, I will propagate it to other places in the tests.
Note that just setting and restoring the settings in a test method (instead of setup and teardown methods) isn't a good idea because if the test fails, the settings won't be restored. Other alternatives I considered are a decorator `@podpac.settings.temporary_settings` that would be applied to specific test methods (a bit harder to implement) and a base …
> Creates a settings context manager for easy temporary settings.

- podpac/core/pipeline/output.py
- podpac/core/test/test_units.py
- podpac/core/units.py
This is a small change, but I think important.
I think its a little opaque to have a single `UnitsDataArray.to_format()` function with different formats and different corresponding args and kwargs. I think its better to write individual methods (i.e. `to_image()`) and then let the `to_format()` function just pick the best one based on the format. This is already mostly the case, but as a user I will look for the `to_image()` method if I'm trying to output the geotiff, not the `to()` method.
Also, `get_image` is not in keeping with the pandas/xarray standard of `to_format..()` for outputs. This again is not that important, but I want to try and keep this as consistent as possible.
> FIX: add `to_image` method to UnitsDataArray and rename `get_image` to `to_image` in units module

- podpac/core/coordinates/coordinates1d.py
- podpac/core/coordinates/test/test_array_coordinates1d.py
- podpac/core/coordinates/test/test_uniform_coordinates1d.py
- podpac/core/coordinates/uniform_coordinates1d.py
- podpac/core/coordinates/utils.py
Consider: 
```
c1 = Coordinates(['2012-05-19'], ['time'])
c2 = Coordinates(['2012-05-19T12:00:00'], ['time'])
c12 = c1.intersect(c2)
c21 = c2.intersect(c1)
```
With this PR, I propose that c12 and c21 should contain an intersection.
> FIX: Fixing time selection when precision is different

- doc/source/api.rst
- podpac/compositor.py
- podpac/core/algorithm/test/test_coord_select.py
- podpac/core/compositor.py
- podpac/core/data/datasource.py
- podpac/core/test/test_compositor.py
- podpac/datalib/smap.py
* Moves `shared_coordinates` and `is_source_coordinates_complete` to `SMAPCompositor`
* Moves set interpolation (and set native_coordinates) from `iteroutputs` to to `select_sources`
* couple of bugfixes
Easy one. In preparation for further compositor work.
> cleanup select sources

- podpac/core/algorithm/coord_select.py
- podpac/core/algorithm/signal.py
- podpac/core/algorithm/stats.py
- podpac/core/algorithm/utility.py
- podpac/core/coordinates/array_coordinates1d.py
- podpac/core/coordinates/coordinates.py
- podpac/core/coordinates/coordinates1d.py
- podpac/core/data/csv_source.py
- podpac/core/data/reprojection.py
- podpac/core/data/test/test_h5py.py
- podpac/core/interpolation/interpolators.py
- podpac/datalib/gfs.py
- podpac/datalib/smap.py
CRS validation with pyproj is very slow, so this is an optimization. For example, when `Coordinates` is subselecting itself in `__getitem__`, it does not need to revalidate the crs.
@mpu-creare @mlshapiro any qualms?
This reduces the runtime for the tests on my machine from 80s to 50s.
> Skip crs Validation when possible

- podpac/core/compositor/compositor.py
- podpac/core/compositor/test/test_base_compositor.py
- podpac/core/compositor/test/test_ordered_compositor.py
- podpac/datalib/cosmos_stations.py
- podpac/datalib/smap.py
Currently Compositors automatic detect `outputs` from the `sources`, which causes deadlock or infinite recursion in fairly normal usage, including SMAP and COSMOS. The problem is quite hard to diagnose, and the workaround is to explicitly set `outputs = None` in these compositor nodes.
The proposed solution is to add a `auto_outputs` flag to Compositors, which defaults to False.
The workaround can be removed from SMAP and COSMOS, and compositor child classes that want to autodetect multiple outputs from sources can enable this feature as follows:
```
class MyCompositor(podpac.core.OrderedCompositor):
auto_outputs = True
```
*Note: either this PR or #388 should be merged, but not both.*
> Bugfix: compositor auto_outputs flag

- podpac/core/cache/cache_ctrl.py
- podpac/core/cache/cache_store.py
- podpac/core/cache/file_cache_store.py
- podpac/core/cache/ram_cache_store.py
- podpac/core/cache/test/test_cache_ctrl.py
- podpac/core/cache/test/test_cache_stores.py
- podpac/core/data/csv_source.py
- podpac/core/data/file_source.py
- podpac/core/data/ogc.py
- podpac/core/data/test/test_csv.py
- podpac/core/data/test/test_file_source.py
- podpac/core/node.py
- podpac/core/test/test_node.py
* raise a `NodeDefinitionError` when a circular node definition is detected
* raise a `NodeDefinitionError` when the node definition is accessed before the node traits are fully initialized
* catch `NodeDefinitionError` in node caching methods and add a more informative message, including the `key`
* cache put methods overwrite/update the cache by default
* `LoadFileMixin` caches the `dataset` independent of the other node attrs (such as `interpolation` or `data_key`).
* `Node.__init__` calls the `tl.HasTraits.__init__` *within* the `hold_trait_notifications` context in order to avoid calling some validation methods before other traits have even ben initialized.
* CacheCtrl is cleaned up, with bugfixes and tests
* small bugfixes in CSV and WCS nodes
The circular node definition handling …
> node definition loops and caching

- podpac/core/algorithm/generic.py
- podpac/core/node.py
- podpac/core/test/test_node.py
- podpac/core/utils.py
* Adds `"podpac_version"` to the node definition.
* Warns about mismatching version when deserializing.
* Omit hash (and style) from hash.
One question: since `__eq__` uses the hash, two nodes can be equal (as in `==`) even if their styles are different. I just want to check if that is what you want, or should equality depend on the json instead (which still includes the style)?
closes #390
> ENH: Add podpac version to node definition.

- dist/aws/handler.py
- podpac/compositor.py
- podpac/core/compositor/compositor.py
- podpac/core/compositor/ordered_compositor.py
- podpac/core/compositor/test/test_base_compositor.py
- podpac/core/compositor/test/test_ordered_compositor.py
- podpac/core/compositor/tile_compositor.py
- podpac/core/data/datasource.py
- podpac/core/data/test/test_datasource.py
- podpac/datalib/modis_pds.py
- podpac/datalib/terraintiles.py
Adds `composite_dims` trait and removes extra dimensions from the evaluation coordinates.
Autodetection could look like this at its simplest:
```
@tl.default("composite_dims")
def _default_composite_dims(self):
return self.sources[0].coordinates.udims
```
> Remove Compositor extra dims using composite_dims

- podpac/core/coordinates/coordinates1d.py
- podpac/core/coordinates/dependent_coordinates.py
- podpac/core/coordinates/stacked_coordinates.py
- podpac/core/coordinates/test/test_coordinates.py
- podpac/core/coordinates/test/test_dependent_coordinates.py
- podpac/core/coordinates/test/test_stacked_coordinates.py
It was missing and breaks the Sentinel datalib (and possibly others).
@jmilloy Would you mind quickly reviewing this -- I want to merge it in for the newest release.
> FIX: Adding issubset function for Dependent Coordinates

- podpac/core/coordinates/array_coordinates1d.py
- podpac/core/coordinates/test/test_coordinates.py
- podpac/core/coordinates/test/test_coordinates_utils.py
- podpac/core/coordinates/utils.py
Problem: 
```python
ct = Coordinates([["2012-05-19T12:00:00", "2012-05-19T13:00:00", "2012-05-20T14:00:00"]], ["time"])
cti = Coordinates([["2012-05-18", "2012-05-19"]], ["time"])
ct2 = ct.intersect(cti, outer=True)
```
This throws in error because `lt` is empty, since `np.datetime64('2020-01-01T00') < np.datetime64('2020-01-01') == False`
As a solution I change the bounds to be the same precision, so `np.datetime('2020-01-01')` --> `np.datetime('2020-01-01T23')`
> FIX: Exception when bounds are lower precision than coordinates

- podpac/core/algorithm/algorithm.py
- podpac/core/algorithm/coord_select.py
- podpac/core/algorithm/reprojection.py
- podpac/core/algorithm/signal.py
- podpac/core/algorithm/stats.py
- podpac/core/compositor/compositor.py
- podpac/core/data/datasource.py
- podpac/core/interpolation/interpolation.py
- podpac/core/managers/multi_process.py
- podpac/core/managers/parallel.py
- podpac/core/managers/test/test_multiprocess.py
- podpac/core/managers/test/test_parallel.py
- podpac/core/node.py
- podpac/core/test/test_node.py
- podpac/datalib/egi.py
- podpac/datalib/satutils.py
* Eliminated `node_eval` decorator, moved functionality into public `eval`
* made specific implementations part of private `_eval` method instead.
* added **kwargs to public `eval` method
> REFACTOR: Eval refactor

- podpac/core/data/datasource.py
The bug that prompted this is that the selected coordinates were not actually being used in `_get_data`.
```
(rsc, rsci) = self.coordinates.intersect(coordinates, outer=True, return_indices=True)
self._requested_source_coordinates = rsc
self._requested_source_coordinates_index = rsci
...
(rsc, rsci) = _selector(rsc, rsci, coordinates)
...
self._requested_source_data = self._get_data(
self._requested_source_coordinates, self._requested_source_coordinates_index
)
```
I think at one point, the `DataSource._evaluated_coordinates`, `Datasource._requested_source_coordinates`, etc were used in other methods. We've been trying to get rid of them in various maintenance tasks for a while. I think with the recent refactors, that is finally the case!
I've kept them as "debug" attributes, but they are …
> Clean up DataSource debug attributes

- podpac/core/algorithm/algorithm.py
- podpac/core/algorithm/generic.py
- podpac/core/algorithm/stats.py
- podpac/core/algorithm/test/test_algorithm.py
- podpac/core/algorithm/utility.py
- podpac/core/coordinates/coordinates.py
- podpac/core/coordinates/test/test_coordinates.py
- podpac/core/data/dataset_source.py
- podpac/core/interpolation/interpolation.py
- podpac/core/interpolation/nearest_neighbor_interpolator.py
- podpac/core/managers/parallel.py
- podpac/core/units.py
- podpac/datalib/drought_monitor.py
- podpac/datalib/egi.py
Backwards Incompatible changes
* removes support for numpy return type from `Algorithm.algorithm`
* passes `coordinates` into `Algorithm.algorithm`. Using `self._requested_coordinates` is no longer necessary.
Fixes
* handles extra, missing, and transposed dimensions returned from `Algorithm.algorithm` correctly when `output` is provided.
Testing
* more comprehensive `Algorithm.algorithm` testing
* test the base `Algorithm` class without using any `Algorithm` subclasses such as `Arange` and `Arithmetic`
Additional Features
* `Coordinates.from_xarray` accepts `DataArray` and `Dataset` types, extracting the `coords` and `crs` as needed. You can still pass in `DataArrayCoordinates` and `DatasetCoordinates`.
> Remove support for numpy return type in Algorithms

- podpac/core/interpolation/interpolation_manager.py
- podpac/core/interpolation/nearest_neighbor_interpolator.py
- podpac/core/interpolation/test/test_interpolators.py
1. Fixes the tests for `test_nearest_preview_select`
* check both lat and lon coordinates
* check the returned coordinates index
2. Fixes the `InterpolationManager.select_coordinates` index reconstruction
* need to reconstruct from the *source* coordinates, not the already selected coordinates
* this fix applies to all interpolators
3. Fixes the `NearestPreview.select_coordinates` coordinates selection.
* It appears that the UniformCoordinates1d `stop` sometimes needs a padding included, but not always. We need a test for both cases.
> BUGFIX: Nearest Preview Select Coordinates

- podpac/core/algorithm/reprojection.py
- podpac/core/algorithm/test/test_reprojection.py
The Reproject algorithm node threw and error in cases where the `reproject_coordinates` do not match the eval coordinates (yikes!)
> FIX: Fixing reproject merge_dims error.

- podpac/core/compositor/compositor.py
- podpac/core/compositor/ordered_compositor.py
- podpac/core/compositor/test/test_ordered_compositor.py
- podpac/core/coordinates/array_coordinates1d.py
- podpac/core/coordinates/coordinates.py
- podpac/core/coordinates/uniform_coordinates1d.py
- podpac/core/data/rasterio_source.py
- podpac/core/interpolation/interpolation_manager.py
- podpac/core/interpolation/xarray_interpolator.py
- podpac/core/node.py
- podpac/core/utils.py
A few performance optimizations and bug fixes.
This PR also add the following features:
* `Compositers.eval_serial`: For some compositors, it's important to actually evaluate the nodes in serial for performance reasons. So, even when multi-threading is used, when this flag is `True` the datasources will be serially evaluated.
* `RasterioSource.prefer_overview_closests`: when selecting overview levels, we can either select the coarsest overview smaller than the user-specified step size (based on eval coordinates) OR we can select the overview with the closest step size to the eval coordinates... this may be coarser than the specified coordinates. Setting this attr to `True` will select the closest overview instead of the closests higher resolution overview.
> Performance Optimizations + A few Bug Fixes

- doc/source/overview.md
- podpac/core/compositor/test/test_tiled_compositor.py
- podpac/core/compositor/tile_compositor.py
- podpac/core/data/datasource.py
- podpac/core/data/ogr.py
- podpac/core/data/test/test_datasource.py
```python3
>>> node = podpac.data.Array(
...             source=np.ones((3, 4)),
...             coordinates=podpac.Coordinates([range(3), range(4)], ["lat", "lon"]),
...         )
>>> 
>>> node.get_source_data()
<xarray.UnitsDataArray (lat: 3, lon: 4)>
array([[1., 1., 1., 1.],
[1., 1., 1., 1.],
[1., 1., 1., 1.]])
Coordinates:
* lat      (lat) float64 0.0 1.0 2.0
* lon      (lon) float64 0.0 1.0 2.0 3.0
Attributes:
layer_style:   <podpac.core.style.Style object at 0x7f7c09fcb730>
crs:           +proj=longlat +datum=WGS84 +no_defs +vunits=m
geotransform:  (-0.5, 1.0, 0.0, -0.5, 0.0, 1.0)
```
```python3
>>> a = ArrayRaw(source=np.arange(5) + 100, coordinates=podpac.Coordinates([[0, 1, 2, 3, 4]], dims=["lat"]))
>>> b = ArrayRaw(source=np.arange(5) + 200, coordinates=podpac.Coordinates([[5, …
```
> Feature: get_source_data

- podpac/core/data/datasource.py
- podpac/core/data/ogr.py
- podpac/core/data/test/test_datasource.py
- podpac/core/interpolation/interpolation.py
- podpac/core/interpolation/test/test_interpolation.py
- podpac/core/node.py
- podpac/core/test/test_node.py
```python
def test_get_bounds(self):
class MyNode(Node):
def find_coordinates(self):
return [
podpac.Coordinates([[0, 1, 2], [0, 10, 20]], dims=["lat", "lon"], crs="EPSG:2193"),
podpac.Coordinates([[3, 4], [30, 40]], dims=["lat", "lon"], crs="EPSG:2193"),
]
node = MyNode()
with podpac.settings:
podpac.settings["DEFAULT_CRS"] = "EPSG:4326"
bounds, crs = node.get_bounds(crs="EPSG:2193")
assert bounds == {"lat": (0, 4), "lon": (0, 40)}
assert crs == "EPSG:2193"
bounds, crs = node.get_bounds()
assert bounds == {
"lat": (-75.81397534013118, -75.81362774074242),
"lon": (82.92787904584206, 82.9280189659297),
}
assert crs == "EPSG:4326"
```
```python
def test_get_bounds(self):
node = podpac.data.Array(
source=np.ones((3, 4)),
coordinates=podpac.Coordinates([range(3), range(4)], ["lat", "lon"], …
```
> ENH: Node get_bounds method.
